### ISSUE TITLE
Cargo crate for gitlab-cargo-audit

### ISSUE THREAD

**Issue by cdesch** [dcoles/gitlab-cargo-audit#1]
Is there a plan to publish this as a crate so it can be installed with something like `cargo install gitlab-cargo-audit`?

**Comment by dcoles** [comment]
Hi @cdesch,

Thanks for creating the issue. I've published the latest version of this package to crates.io ([`gitlab-cargo-audit` v0.3.0](https://crates.io/crates/gitlab-cargo-audit/0.3.0)).

It should be installable with `cargo install gitlab-cargo-audit` like you suggested.

Please let me know if you run into any issues.
