### ISSUE TITLE
Release the crate with the new `--output-path` option

### ISSUE THREAD

**Issue by peddermaster2** [dcoles/gitlab-cargo-audit#11]
It would be nice if we can get a new release to crates.io that includes the `--output-path`  option.  
Otherwise one has to `cargo install` this package from source or git to get the new feature.

**Comment by dcoles** [comment]
Hi @peddermaster2. Thank you for the reminder. I also seem to have missed it for the `0.4.0` release.

[`github-cargo-audit-0.5.0`](https://crates.io/crates/gitlab-cargo-audit/0.5.0) should now be available on crates.io. Please let me know if you encounter any issues.
