### ISSUE TITLE
Cargo lockfile format v4 unsupported

### ISSUE THREAD

**Issue by PaulDance** [dcoles/gitlab-cargo-audit#14]
Dear maintainer,

Using the current version with the v4 format of the Cargo lockfile introduced in 1.83 ends up in an error:

```console
$ gitlab-cargo-audit
Error: failed to load lockfile
Caused by:
    parse error: parse error: invalid Cargo.lock format version: `4`
    
Stack backtrace:
   0: gitlab_cargo_audit::main
   1: std::sys::backtrace::__rust_begin_short_backtrace
   2: std::rt::lang_start::{{closure}}
   3: std::rt::lang_start_internal
   4: main
   5: __libc_start_call_main
   6: __libc_start_main_alias_2
   7: _start
```

This most probably caused by `rustsec::cargo_lock` that does not yet recognize the new version number. The currently used version of the crate is 0.29 while 0.30 supports the v4 format.

Would it therefore be possible to bump the dependency, test that the patch works with the v4 format and publish a new version with it?

Thanks in advance,
Paul.

**Comment by dcoles** [comment]
Fixed by 6f5914004ee6f15d1a5cd36c7c68ffc96271f5e9.

**Comment by dcoles** [comment]
@PaulDance Thanks for opening this issue. I've made the suggested changes and published a [0.6.0 crate](https://crates.io/crates/gitlab-cargo-audit/0.6.0). I tested this with `gitlab-cargo-audit`'s own lock-file which was got updated while I was making the change.

Please let me know if that works or if hit some issue with the new release.

**Comment by PaulDance** [comment]
Cool, thanks! I'm sure it's working just fine now, but I'll let you know in case something else pops up, yes.

**Comment by PaulDance** [comment]
Update: just tested it in our CI environment, and everything seems to behave well. Thanks!
