### ISSUE TITLE
Error: failed to load lockfile

### ISSUE THREAD

**Issue by p-alik** [dcoles/gitlab-cargo-audit#2]
Run into https://github.com/dcoles/gitlab-cargo-audit/blob/d628298e3a437ebbeb021ae7bfb4896b2d9373fb/src/main.rs#L24 because `Cargo.lock` is not a part of the repo
```
$ $CARGO_HOME/bin/gitlab-cargo-audit
Error: failed to load lockfile
Caused by:
    I/O operation failed: NotFound
```
Might be good to check if `Cargo.lock` exists

**Comment by dcoles** [comment]
Hi @p-alik. Thanks for the bug report.

Our CI/CD pipeline always called `cargo check` prior to `gitlab-cargo-audit`, which had the side-effect of also generating `Cargo.lock` for crates without one. This tool now calls `cargo generate-lockfile` if it appears that `Cargo.lock` is missing (the same approach taken by `cargo-audit`).

**Comment by p-alik** [comment]
thank you, @dcoles!
